ci: add testing job for operator

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -1,4 +1,4 @@
-name: 'Build container images'
+name: 'Test go packages and build container images'
 
 on:
   push:
@@ -32,9 +32,94 @@ jobs:
   #         daemon: ['daemon/**', 'api/**', 'go.work', 'go.work.sum']
   #         operator: ['operator/**', 'api/**', 'go.work', 'go.work.sum']
 
+  test-and-coverage:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    strategy:
+      matrix:
+        target: ['operator']
+    env:
+      ENVTEST_K8S_VERSION: 1.34.1
+      GINKGO_NO_COLOR: TRUE
+
+    steps:
+      - run: echo "$ENVTEST_K8S_VERSION" > k8sver
+      - uses: actions/checkout@v7
+        with:
+          fetch-depth: 2
+
+      - name: Set up Go
+        id: setupgo
+        uses: actions/setup-go@v6
+        with:
+          go-version: '1.26.2'
+          cache: true
+          #cache-dependency-path: '**/go.mod'
+          cache-dependency-path: |
+            k8sver
+            tools/go.mod
+            operator/go.mod
+
+      - name: Cache envtest
+        id: cache-envtest
+        uses: actions/cache@v6
+        with:
+          path: tools/bin
+          key: "envtest-${{ env.ENVTEST_K8S_VERSION }}"
+
+      - name: Run setup-envtest
+        run: |
+          echo "KUBEBUILDER_ASSETS=${{ github.workspace }}/tools/$(go -C tools tool setup-envtest use ${ENVTEST_K8S_VERSION} --bin-dir ./bin -p path)" >> "$GITHUB_ENV"
+
+      - name: Run tests with coverage
+        run: |
+          set +e
+          go -C tools tool gotestsum --no-color --junitfile unit-tests.xml -- -coverprofile=coverage.out ../operator/...
+          test_exit_code=$?
+          ls -lah tools
+          go tool cover -html=./tools/coverage.out -o ./tools/coverage.html
+          go -C tools tool gocover-cobertura < ./tools/coverage.out > ./tools/coverage.xml
+          exit "$test_exit_code"
+
+      #- name: Publish Test Report
+      #  uses: mikepenz/action-junit-report@v6
+      #  if: success() || failure() # always run even if the previous step fails
+      #  with:
+      #    report_paths: unit-tests.xml
+      #    detailed_summary: true
+      #    include_passed: true
+      #    include_time_in_summary: true
+
+      - name: Generate unit test summary
+        if: "!cancelled()"
+        uses: test-summary/action@v2
+        with:
+          paths: "tools/unit-tests.xml"
+
+      - name: Generate coverage summary
+        if: "!cancelled()"
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: "./tools/coverage.xml"
+          format: markdown
+          output: file
+
+      - name: Upload coverage as artifact
+        if: "!cancelled()"
+        uses: actions/upload-artifact@v7
+        with:
+          path: "tools/coverage.html"
+          archive: false
+
+      - name: Write coverage to job summary
+        if: "!cancelled()"
+        run: cat ./code-coverage-results.md >> $GITHUB_STEP_SUMMARY
+
   build-and-push:
     runs-on: ubuntu-latest
     # needs: changes
+    needs: test-and-coverage
     permissions:
       contents: read
       packages: write
